[package]
name = "refinedpy_lsp"
version = "1.3.0-dev.1"
authors = ["TypeRefinery"]
edition = "2024"

[lib]
path = "src/lib.rs"

[[bin]]
name = "refinedpy-lsp"
path = "src/bin/refinedpy-lsp.rs"

[dependencies]
anyhow = "1.0.104"
clap = { version = "4.6.2", features = ["cargo", "derive", "env", "string", "unicode", "wrap_help"] }
lsp-types = { git = "https://github.com/yangdanny97/lsp-types", rev = "395d6bfcd6c3696a64cfe9cd93b86f981fb85112" }
pyrefly = { path = "../../pyrefly" }
pyrefly_build = { path = "../pyrefly_build" }
pyrefly_python = { path = "../pyrefly_python" }
pyrefly_util = { path = "../pyrefly_util" }
refined_kernel = { path = "../../../rust/refined_kernel" }
refined_sets = { path = "../../../rust/refined_sets" }
refinedpy = { path = "../refinedpy" }
ruff_python_ast = { version = "0.0.6", features = ["serde"] }
ruff_python_parser = "0.0.6"
ruff_text_size = "0.0.6"
serde_json = { version = "1.0.151", features = ["alloc", "float_roundtrip", "raw_value", "unbounded_depth"] }
tokio = { version = "1.53.1", features = ["macros", "rt"] }

[target.'cfg(any(target_os = "linux", target_os = "macos"))'.dependencies]
tikv-jemallocator = "0.6.1"

[target.'cfg(target_os = "windows")'.dependencies]
mimalloc = { version = "0.1.52", default-features = false }
